### ISSUE TITLE
앞으로의 개발 방향성

### ISSUE THREAD

**Issue by Gerbera3090** [jbs30lcy/Thief-Poker#12]
1. 나중에 다 묶어서 exe 파일로 만들어서 배포해야 함. 이건 뭐 잘 할수 있지? 알아만 두자고
2. 디렉터용 프로그램을 따로 만들어서 디렉터가 게임의 진행을 컨트롤 가능하게 하자. ex) 학생들 모두 접속한 후 게임 초기화, 매 라운드 매칭 순서 배정 등등 그래서 초기화 부분은 그쪽을 생각하면 될 듯?

**Comment by jbs30lcy** [comment]
디렉터용 파일 만들사람 구함
나는 너무 귀차나

**Comment by jbs30lcy** [comment]
매칭 순서는 스프레드시트 한쪽에 우리가 미리 정해서 넣어놓자. 디렉터 파일 중에 꼭 필요한게 있는데
혹시 애들이 하다가 오류가 터졌을 때, 스프레드시트를 임의로 조작해서 오류를 해결할 수 있도록 해야됨. 진짜 최악이지만 혹시 족보 계산에서 터지면 그 족보가 못 나오도록 막 바꿔버리고 그래ㅑㅣ야 할 수도 있음

그리고 예를들어 5라운드 뒤에 미니게임을 하든가 하면, 게임을 계속 진행할 것인가? 에 대한 flag 변수를 스프레드시트 한쪽에 넣어야 하고, 디렉터가 5라운드 중간에 디렉터 프로그램으로 그 변수를 False로 만들어 게임 진행을 중간에 막아야됨.

**Comment by ksiwon** [comment]
오류 방지 직접 스프레드시트에 올릴 수 있는 디렉터용 코드를 만들어야 할 듯.
지난 번 시빌 워 때 나 혼자 돌릴려고 만든 1인 플레이 스프레드시트처럼 만들면 되지 않을까?
