### ISSUE TITLE
화면 크기

### ISSUE THREAD

**Issue by jbs30lcy** [jbs30lcy/Thief-Poker#2]
현재 (1600, 900)
박정원이 노트북이 째끄매서
크기를 유동적으로 조절할 수 있도록 해야됨

**Comment by ksiwon** [comment]
팩트) 내 해상도에는 문제가 없다. 해상도 1920X1080인거 확인함. 일단 큰 화면보단 작은 화면에 우선적으로 맞추는게?

**Comment by jbs30lcy** [comment]
내일쯤 기가막힌 방식으로 처리해드림.
